accelerate launch fine-tune-dp.py \
--output_dir outputs/phi3.5-mini-echr-dp-eps8 \
--model_name microsoft/Phi-3.5-mini-instruct \
--target_modules all-linear \
--sequence_len 512 \
--per_device_train_batch_size 8 \
--gradient_accumulation_steps 2 \
--eval_strategy no \
--log_level info \
--per_device_eval_batch_size 8 \
--eval_accumulation_steps 1 \
--seed 42 \
--target_epsilon 8 \
--per_sample_max_grad_norm 1.0 \
--remove_unused_columns False \
--num_train_epochs 4 \
--logging_steps 10 \
--learning_rate 1e-4 \
--label_names labels \
--enable_lora True \
--save_strategy no \
--lr_scheduler_type constant