bash exps/scripts/Gtab-analyze_echr_llama.sh > Logs/gtab-analyze_echr_llama.log 2>&1
bash exps/scripts/Gtab-analyze_echr_gemma.sh > Logs/gtab-analyze_echr_gemma.log 2>&1
bash exps/scripts/Gtab-analyze_echr_qwen.sh > Logs/gtab-analyze_echr_qwen.log 2>&1
bash exps/scripts/Gtab-analyze_echr_phi.sh > Logs/gtab-analyze_echr_phi.log 2>&1
bash exps/scripts/Gtab-analyze_enron_llama.sh > Logs/gtab-analyze_enron_llama.log 2>&1
bash exps/scripts/Gtab-analyze_enron_gemma.sh > Logs/gtab-analyze_enron_gemma.log 2>&1
bash exps/scripts/Gtab-analyze_enron_qwen.sh > Logs/gtab-analyze_enron_qwen.log 2>&1
bash exps/scripts/Gtab-analyze_enron_phi.sh > Logs/gtab-analyze_enron_phi.log 2>&1
bash exps/scripts/Gtab-analyze_llm_pc_llama.sh > Logs/gtab-analyze_llm_pc_llama.log 2>&1
bash exps/scripts/Gtab-analyze_llm_pc_gemma.sh > Logs/gtab-analyze_llm_pc_gemma.log 2>&1
bash exps/scripts/Gtab-analyze_llm_pc_qwen.sh > Logs/gtab-analyze_llm_pc_qwen.log 2>&1
bash exps/scripts/Gtab-analyze_llm_pc_phi.sh > Logs/gtab-analyze_llm_pc_phi.log 2>&1
